# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goclone < Formula
  desc "goclone - clone websites in a matter of seconds."
  homepage "https://github.com/shurco/goclone"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shurco/goclone/releases/download/v1.0.3/goclone_1.0.3_darwin-arm64.tar.gz"
      sha256 "7e74a38582408c76288cdfd1bd9b18ca81eb205f8541e42c3074c00edcad5e62"

      def install
        bin.install "goclone"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shurco/goclone/releases/download/v1.0.3/goclone_1.0.3_darwin-amd64.tar.gz"
      sha256 "8104a1037731e50385b98c605fad54b4ad3ef45f209a31069bb28e94398baced"

      def install
        bin.install "goclone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/shurco/goclone/releases/download/v1.0.3/goclone_1.0.3_linux-amd64.tar.gz"
      sha256 "62a1422ad53e8169c3805546d34281d5b035ea469b5ff033b04a38309e2322e5"

      def install
        bin.install "goclone"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shurco/goclone/releases/download/v1.0.3/goclone_1.0.3_linux-arm64.tar.gz"
      sha256 "cd17c9dcc2bed782dff128ad9c365b83e549f18ff8a1609f963c252730e6e82c"

      def install
        bin.install "goclone"
      end
    end
  end
end
