# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goclone < Formula
  desc "Website Cloner - Utilizes powerful Go routines to clone websites to your computer within seconds."
  homepage "https://github.com/shurco/goclone"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shurco/goclone/releases/download/v1.0.0/goclone_1.0.0_darwin-amd64.tar.gz"
      sha256 "d6c7efdc2802e95c6c57ec1d5c8ee7a7e5245bf8b652e54a3416ba6db4449345"

      def install
        bin.install "goclone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shurco/goclone/releases/download/v1.0.0/goclone_1.0.0_darwin-arm64.tar.gz"
      sha256 "358326c59161325093819dcde67976ffef42e73faec2ebeaa29aa018f792142f"

      def install
        bin.install "goclone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shurco/goclone/releases/download/v1.0.0/goclone_1.0.0_linux-arm64.tar.gz"
      sha256 "e348796a4c499ee23177660a44a7574eeefc61fd2db275c22d70829bc3a25aa4"

      def install
        bin.install "goclone"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shurco/goclone/releases/download/v1.0.0/goclone_1.0.0_linux-amd64.tar.gz"
      sha256 "7f2d457bf5b5daee178efde463777e2a435caf85d2607a9c14d523e68f0b0bb0"

      def install
        bin.install "goclone"
      end
    end
  end
end
