# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Litecart < Formula
  desc "🛒 litecart - shopping-cart in 1 file"
  homepage "https://github.com/shurco/litecart"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shurco/litecart/releases/download/v0.1.0/litecart_0.1.0_darwin-arm64.tar.gz"
      sha256 "1fc1ee31c940b2c68f7ca1a62a45409bb09b1cc0f57cd868342714c40c5f4a01"

      def install
        bin.install "litecart"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shurco/litecart/releases/download/v0.1.0/litecart_0.1.0_darwin-amd64.tar.gz"
      sha256 "e3b96af770b07e2e38bd98aaed8da94714330c6838ddc6fddd2ff5a05b85c479"

      def install
        bin.install "litecart"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shurco/litecart/releases/download/v0.1.0/litecart_0.1.0_linux-arm64.tar.gz"
      sha256 "cee632fedc07c3c5cef234399e00ad55d1a00af19d8808eb7d59832947b2024e"

      def install
        bin.install "litecart"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shurco/litecart/releases/download/v0.1.0/litecart_0.1.0_linux-amd64.tar.gz"
      sha256 "3f20f718f03886281e3804abdd721bc36587c2105ed0dd18e05261fcea0b0c62"

      def install
        bin.install "litecart"
      end
    end
  end
end
