# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Litecart < Formula
  desc "🛒 litecart - shopping-cart in 1 file"
  homepage "https://github.com/shurco/litecart"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shurco/litecart/releases/download/v0.1.5/litecart_0.1.5_darwin-arm64.tar.gz"
      sha256 "379991668fc93abde2c8a2fe00d8ee8cb3af57a5c1663d04e93fdddc1b840d35"

      def install
        bin.install "litecart"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shurco/litecart/releases/download/v0.1.5/litecart_0.1.5_darwin-amd64.tar.gz"
      sha256 "0840c21fc17cc84afdf250f705aeebc4965b253daad8a185abc9c5b83a850836"

      def install
        bin.install "litecart"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shurco/litecart/releases/download/v0.1.5/litecart_0.1.5_linux-arm64.tar.gz"
      sha256 "0fe162a74c67a5a14a590695834061078cf578c5418db169f0f838ede5d25197"

      def install
        bin.install "litecart"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shurco/litecart/releases/download/v0.1.5/litecart_0.1.5_linux-amd64.tar.gz"
      sha256 "5345151758f31e630671274bff463942e503f19be2f5c3cfbb3b8e45a3cc84c9"

      def install
        bin.install "litecart"
      end
    end
  end
end
