# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Litecart < Formula
  desc "🛒 litecart - shopping-cart in 1 file"
  homepage "https://github.com/shurco/litecart"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shurco/litecart/releases/download/v0.1.0/litecart_0.1.0_darwin-amd64.tar.gz"
      sha256 "92807a8b8c859fe7ae6ba76eb0175b925e48683719eaebd0338d95de32e33a71"

      def install
        bin.install "litecart"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shurco/litecart/releases/download/v0.1.0/litecart_0.1.0_darwin-arm64.tar.gz"
      sha256 "4eb62cfbb4aeb84af36431af74db4ec69342282e0822839ed22a7d216395bd3c"

      def install
        bin.install "litecart"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/shurco/litecart/releases/download/v0.1.0/litecart_0.1.0_linux-amd64.tar.gz"
      sha256 "69d3d0ff421b3e31cbb557b8185f06f1f57abd9edc80ff72b5e9d6fe413570af"

      def install
        bin.install "litecart"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shurco/litecart/releases/download/v0.1.0/litecart_0.1.0_linux-arm64.tar.gz"
      sha256 "25d96ca5224f50e84f8e0af7862f22f1609c360fbfe4a4073de99a52e4ed4c20"

      def install
        bin.install "litecart"
      end
    end
  end
end
